### ISSUE TITLE
Syntax bugs cause render failure with minimal response, PG warnings not making it to the display

### ISSUE THREAD

**Issue by taniwallach** [rederly/renderer#31]
A PG file with a syntax error causes minimal debugging data to be provided.(Tested with master from 2021-Jan-18. at 30d35261e80c6c0c68445c7f9d551facb7c32ba0)

Below is a small example (with an intentional bug).
  - Uncommenting the `"MathObjects.pl",` line fixes the issue in the PG code.
  - But the issue with the standalone renderer is that it fails to provide the debugging output.
---
```
DOCUMENT();
loadMacros(
  "PGstandard.pl",
#  "MathObjects.pl",
);

BEGIN_TEXT
Calculate \( 2 \cdot 3 \)
and enter the result: \{ ans_rule(4) \}.
END_TEXT

ANS( Real(6)->cmp() );

ENDDOCUMENT();
```
---

The rendered problem section shows:
![2021-01-18_22-35](https://user-images.githubusercontent.com/39089094/104960811-aa048700-59dd-11eb-8ad2-5bff18401f18.png)

```
        Problem 1
2. ERROR caught by Translator while processing this problem 
```

The developer mode shows the response as containing the following in the JSON structure:
```
"debug" : {
  "debug":null,
  "internal":["Error in obtaining debug messages from PGcore"],
  "perl_warn":"",
  "pg_warn":null,
  "render_warn":[]
},
```

---

When a regular WW 2.15 server tries to render this problem, the error output is:
```
        Problem1
1. ERROR caught by Translator while processing problem file:5.pg
****************
ERRORS from evaluating PG file: 
 Undefined subroutine &main::Real called at line 12 of (eval 3840)



****************

------Input Read
1		DOCUMENT();
2		loadMacros(
3		  "PGstandard.pl",
4		#  "MathObjects.pl",
5		);
6		
7		BEGIN_TEXT
8		Calculate \( 2 \cdot 3 \)
9		and enter the result: \{ ans_rule(4) \}.
10		END_TEXT
11		
12		ANS( Real(6)->cmp() );
13		
14		ENDDOCUMENT();


```

**Comment by doombot-exe** [comment]
this issue is fixed with an update to the permissionLevel when rendering from the standalone renderer. 

Be aware, this change prevents the checkboxes 'show hints' and 'show solutions' from affecting the render. I think they will likely just be removed, and perhaps replaced with the optional psvn that was requested.

**Comment by taniwallach** [comment]
> and perhaps replaced with the optional psvn that was requested.
`psvn` is not really related to that. It is a special random seed value expected by "chains" of problems which need a common seed.

**Comment by taniwallach** [comment]
Fixed by https://github.com/rederly/renderer/pull/37
