### ISSUE TITLE
Proposed "raw" json output format from the main project of probably relevance for the standalone renderer

### ISSUE THREAD

**Issue by taniwallach** [rederly/renderer#4]
See: https://github.com/openwebwork/webwork2/pull/1120 by @Alex-Jordan which proposes adding a "raw" output format which provides a JSON object with essentially everything the renderer produced, to allow a client system access to the structured data for additional processing.

Such an output format may be quite useful in the contexts where the standalone renderer can be of use, assuming the system making the request can do significant post-processing.

**Comment by doombot-exe** [comment]
By making your request with `format: 'json'` this renderer will give you (more or less) exactly what you're asking for here.

**Comment by taniwallach** [comment]
Sorry - I saw the file at https://github.com/rederly/renderer/blob/master/lib/WeBWorK/lib/WebworkClient/json_format.pl and assumed that it was being used.
